#spring.application.name=freshAndFit

spring:
  application:
    name: freshAndFit
  datasource:
    url: jdbc:postgresql://localhost:5432/freshandfit
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
