#spring.application.name=freshAndFit

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: you
            client-secret: grgijig
            scope:
              - email
              - phone
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-authentication-method: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
  application:
    name: freshAndFit
  datasource:
    url: jdbc:postgresql://localhost:5432/freshandfit
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
paypal:
  client-id: AapZH6kbtizw_ZpKFZWNGJRFGuwMq8yMnrFr9yQgul96ajQQgsic1fvPeRGPJYUc4e1wi9sX1IdPJ0Zs
  client-secret: EEEeMXJDYm3UDXg7cXaKXbxxhDDFJmM8htxi0AO-A1vqeEulBW9xAVzoASW2BsgY725ej4btDpGnoUnW
  mode: sandbox #live
app:
  sendGrid-key: jjjjjkjkjkjkjk
  sendGrid-email: freshAndFit@gmail.com
  sendGrid-name: fresh and fit
  twilio-phoneNumber: 09090909909
  twilio-key: 09090909909
  twilio-secret: 09090909909

monnify:
    base-url: https://sandbox.monnify.com/api/v1 # Use production URL for live environment
    api-key: MK_TEST_XZTTBNSLH6
    secret-key: R6ZRBEBGTWAH8ZW2B54SJQPB88B8SBRW
    contract-code: 9585229885

twilio:
  account-sid: your_account_sid
  auth-token: your_auth_token
  from-phone-number: your_twilio_phone_number
logging:
   level:
    org.springframework.security: TRACE


